<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { Head, router, usePage } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';

const page = usePage<any>(); const search = ref(''); const selectedCategory = ref('Semua'); const outletId = ref(page.props.defaultOutletId ?? ''); const processing = ref(false); const localError = ref('');
const paymentMethod = ref('cash'); const paidAmount = ref(0); const split = ref(false); const secondMethod = ref('qris'); const secondAmount = ref(0); const discount = ref(0); const notes = ref(''); const autoPrint = ref(false);
const newCheckoutToken = () => globalThis.crypto?.randomUUID?.() ?? '00000000-0000-4000-8000-' + Date.now().toString().padStart(12, '0').slice(-12);
const checkoutToken = ref(newCheckoutToken());
const cart = reactive<Record<number, number>>({}); const itemNotes = reactive<Record<number, string>>({}); const heldOrder = ref<any>(null);
const menus = computed<any[]>(() => page.props.menus ?? []); const categories = computed<string[]>(() => ['Semua', ...Array.from(new Set<string>(menus.value.map((menu: any) => String(menu.category)).filter(Boolean)))]);
const filteredMenus = computed(() => menus.value.filter((menu: any) => (selectedCategory.value === 'Semua' || menu.category === selectedCategory.value) && (menu.name.toLowerCase().includes(search.value.trim().toLowerCase()) || menu.barcode?.includes(search.value.trim()))));
const cartRows = computed(() => menus.value.filter((menu: any) => cart[menu.id]).map((menu: any) => ({ ...menu, quantity: cart[menu.id], subtotal: Number(menu.price) * cart[menu.id] })));
const itemCount = computed(() => cartRows.value.reduce((sum: number, row: any) => sum + row.quantity, 0)); const subtotal = computed(() => cartRows.value.reduce((sum: number, row: any) => sum + row.subtotal, 0)); const total = computed(() => Math.max(0, subtotal.value - Math.min(Number(discount.value || 0), subtotal.value)));
const paymentTotal = computed(() => Number(paidAmount.value || 0) + (split.value ? Number(secondAmount.value || 0) : 0)); const change = computed(() => Math.max(0, paymentTotal.value - total.value));
const checkoutError = computed(() => page.props.errors?.checkout ?? page.props.errors?.items ?? page.props.errors?.payments ?? page.props.errors?.paid_amount ?? page.props.errors?.outlet_id ?? localError.value); const canCheckout = computed(() => Boolean(outletId.value) && cartRows.value.length > 0 && paymentTotal.value >= total.value && !processing.value);
const canCreate = computed(() => Boolean(page.props.auth?.permissions?.Pos?.can_create));
const heldOrderKey = computed(() => `sedia-held-order:${page.props.auth?.user?.id ?? 'guest'}:${outletId.value || 'none'}`);
const rupiah = (value: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);

watch(total, () => { paidAmount.value = total.value; secondAmount.value = 0; localError.value = ''; });
watch(split, () => { paidAmount.value = total.value; secondAmount.value = 0; if (secondMethod.value === paymentMethod.value) secondMethod.value = paymentMethod.value === 'cash' ? 'qris' : 'cash'; });
watch(paymentMethod, () => { if (secondMethod.value === paymentMethod.value) secondMethod.value = paymentMethod.value === 'cash' ? 'qris' : 'cash'; if (!split.value) paidAmount.value = total.value; });
function add(menu: any) { const maximum = menu.available_quantity === null ? 999 : menu.available_quantity; if ((cart[menu.id] ?? 0) < maximum) cart[menu.id] = (cart[menu.id] ?? 0) + 1; else localError.value = `Stok ${menu.name} maksimal ${maximum} porsi.`; }
function decrement(menu: any) { if ((cart[menu.id] ?? 0) <= 1) remove(menu); else cart[menu.id]--; }
function remove(menu: any) { delete cart[menu.id]; delete itemNotes[menu.id]; }
function clearCart() { Object.keys(cart).forEach((id) => delete cart[Number(id)]); Object.keys(itemNotes).forEach((id) => delete itemNotes[Number(id)]); discount.value = 0; notes.value = ''; paymentMethod.value = 'cash'; paidAmount.value = 0; split.value = false; secondMethod.value = 'qris'; secondAmount.value = 0; localError.value = ''; }
function scan() { const menu = menus.value.find((item: any) => item.barcode && item.barcode === search.value.trim()); if (menu) { add(menu); search.value = ''; } }
function changeOutlet() { clearCart(); router.get('/app/pos', { outlet_id: outletId.value }, { preserveState: false, replace: true }); }
function holdOrder() { if (!cartRows.value.length || (heldOrder.value && !confirm('Ganti pesanan tertahan untuk outlet ini?'))) return; const order = { cart: { ...cart }, itemNotes: { ...itemNotes }, discount: discount.value, notes: notes.value, outletId: outletId.value }; localStorage.setItem(heldOrderKey.value, JSON.stringify(order)); heldOrder.value = order; clearCart(); }
function restoreOrder() { if (!heldOrder.value || Number(heldOrder.value.outletId) !== Number(outletId.value) || (cartRows.value.length && !confirm('Ganti keranjang saat ini dengan pesanan tertahan?'))) return; clearCart(); Object.assign(cart, heldOrder.value.cart); Object.assign(itemNotes, heldOrder.value.itemNotes); discount.value = Number(heldOrder.value.discount || 0); notes.value = heldOrder.value.notes || ''; localStorage.removeItem(heldOrderKey.value); heldOrder.value = null; }
function checkout() { if (processing.value) return; localError.value = ''; if (!outletId.value) localError.value = 'Pilih outlet sebelum checkout.'; else if (!cartRows.value.length) localError.value = 'Tambahkan minimal satu menu ke keranjang.'; else if (split.value && secondMethod.value === paymentMethod.value) localError.value = 'Pilih metode pembayaran kedua yang berbeda.'; else if (paymentTotal.value < total.value) localError.value = 'Jumlah pembayaran masih kurang.'; if (localError.value) return;
    const payments = [{ method: paymentMethod.value, amount: Number(paidAmount.value) }, ...(split.value && secondAmount.value > 0 ? [{ method: secondMethod.value, amount: Number(secondAmount.value) }] : [])];
    processing.value = true; router.post('/app/pos/checkout', { checkout_token: checkoutToken.value, outlet_id: outletId.value, payment_method: paymentMethod.value, paid_amount: paymentTotal.value, payments, discount_amount: discount.value, notes: notes.value, items: cartRows.value.map((row: any) => ({ menu_item_id: row.id, quantity: row.quantity, notes: itemNotes[row.id] || null })) }, { preserveScroll: true, onSuccess: (response: any) => { clearCart(); checkoutToken.value = newCheckoutToken(); if (autoPrint.value && response.props.flash?.receipt_url) window.open(response.props.flash.receipt_url, '_blank'); }, onFinish: () => { processing.value = false; } });
}
onMounted(() => { const saved = localStorage.getItem(heldOrderKey.value); if (saved) try { const order = JSON.parse(saved); if (Number(order.outletId) === Number(outletId.value)) heldOrder.value = order; else localStorage.removeItem(heldOrderKey.value); } catch { localStorage.removeItem(heldOrderKey.value); } });
</script>

<template><Head title="POS"/><AppLayout><template #title>POS Kasir</template><div class="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-[minmax(0,1fr)_400px]">
<section class="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><span class="size-2 rounded-full bg-emerald-500"></span><p class="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-700">Kasir aktif</p></div><h2 class="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Pilih menu</h2></div><select v-if="page.props.auth?.user?.role === 'admin'" v-model="outletId" class="rounded-xl border-slate-200 bg-slate-50 text-sm" @change="changeOutlet"><option value="" disabled>Pilih outlet</option><option v-for="(name, id) in page.props.outlets" :key="id" :value="Number(id)">{{ name }}</option></select></div>
<div class="mb-5 space-y-3"><div class="relative"><span class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" aria-hidden="true">⌕</span><input v-model="search" aria-label="Cari menu atau scan barcode" class="w-full rounded-xl border-slate-200 bg-slate-50 py-3 pl-10 pr-4 text-sm" placeholder="Cari nama atau scan barcode..." @keyup.enter="scan"></div><div class="flex gap-2 overflow-x-auto pb-1" aria-label="Kategori menu"><button v-for="category in categories" :key="category" :aria-pressed="selectedCategory === category" class="whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold" :class="selectedCategory === category ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-500 hover:bg-slate-200'" @click="selectedCategory = category">{{ category }}</button></div></div>
<div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><button v-for="menu in filteredMenus" :key="menu.id" :disabled="menu.available_quantity === 0" class="group rounded-xl border border-slate-200 bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-cyan-300 hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-50" @click="add(menu)"><div class="flex items-start justify-between gap-2"><span class="rounded-md bg-slate-100 px-2 py-1 text-[9px] font-bold uppercase text-slate-500">{{ menu.category || 'Menu' }}</span><span class="text-[10px] font-semibold" :class="menu.available_quantity === 0 ? 'text-rose-600' : 'text-emerald-600'">{{ menu.available_quantity === null ? 'Tanpa batas resep' : `Stok ${menu.available_quantity}` }}</span></div><div class="mt-7 flex items-end justify-between"><div><p class="font-semibold text-slate-900">{{ menu.name }}</p><p class="mt-1 text-sm font-bold text-cyan-700">{{ rupiah(Number(menu.price)) }}</p></div><span class="grid size-9 place-items-center rounded-lg bg-cyan-50 font-bold text-cyan-700 group-hover:bg-cyan-500 group-hover:text-slate-950">{{ cart[menu.id] || '+' }}</span></div></button><div v-if="!filteredMenus.length" class="col-span-full rounded-xl border border-dashed border-slate-300 py-14 text-center text-sm text-slate-500">Menu tidak ditemukan.</div></div></section>
<aside class="h-fit overflow-hidden rounded-2xl bg-slate-950 text-white shadow-xl xl:sticky xl:top-5"><div class="border-b border-white/10 p-5"><div class="flex items-center justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-400">Pesanan saat ini</p><h2 class="mt-1 text-lg font-semibold">Keranjang</h2></div><div class="flex gap-3"><button v-if="heldOrder" class="text-xs text-amber-300" @click="restoreOrder">Pulihkan</button><button v-if="cartRows.length" class="text-xs text-slate-500 hover:text-rose-400" @click="clearCart">Kosongkan</button></div></div><div class="mt-3 flex gap-2 text-xs"><span class="rounded-lg bg-white/[0.07] px-2.5 py-1">{{ itemCount }} produk</span><button v-if="cartRows.length" class="rounded-lg bg-amber-400/10 px-2.5 py-1 text-amber-300" @click="holdOrder">Tahan pesanan</button></div></div>
<div class="max-h-[320px] min-h-[130px] space-y-3 overflow-y-auto p-5" aria-live="polite"><div v-for="row in cartRows" :key="row.id" class="rounded-xl bg-white/[0.06] p-3"><div class="flex justify-between"><div><p class="text-sm font-medium">{{ row.name }}</p><p class="text-xs text-slate-500">{{ rupiah(Number(row.price)) }}</p></div><button :aria-label="`Hapus ${row.name}`" class="text-slate-600 hover:text-rose-400" @click="remove(row)">×</button></div><div class="mt-3 flex items-center justify-between"><div class="flex items-center gap-2"><button :aria-label="`Kurangi ${row.name}`" class="grid size-7 place-items-center rounded-lg bg-white/10" @click="decrement(row)">−</button><span class="w-6 text-center text-sm">{{ row.quantity }}</span><button :aria-label="`Tambah ${row.name}`" class="grid size-7 place-items-center rounded-lg bg-white/10" @click="add(row)">+</button></div><strong class="text-sm text-cyan-300">{{ rupiah(row.subtotal) }}</strong></div><input v-model="itemNotes[row.id]" :aria-label="`Catatan ${row.name}`" maxlength="255" class="mt-2 w-full rounded-lg border-white/10 bg-white/[0.05] text-xs text-white" placeholder="Catatan item..."></div><div v-if="!cartRows.length" class="grid min-h-[130px] place-items-center text-sm text-slate-500">Keranjang masih kosong.</div></div>
<div class="border-t border-white/10 bg-white/[0.03] p-5"><div v-if="checkoutError" role="alert" class="mb-3 rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-xs text-rose-200"><strong class="block text-rose-300">Checkout belum berhasil</strong>{{ checkoutError }}</div><div class="space-y-2 text-sm"><div class="flex justify-between text-slate-400"><span>Subtotal</span><span>{{ rupiah(subtotal) }}</span></div><label class="flex items-center justify-between text-slate-400"><span>Diskon</span><input v-model.number="discount" type="number" min="0" :max="subtotal" class="w-32 rounded-lg border-white/10 bg-white/[0.07] py-1.5 text-right text-white"></label><div class="flex justify-between border-t border-white/10 pt-2"><strong>Total</strong><strong class="text-lg text-cyan-300">{{ rupiah(total) }}</strong></div></div><textarea v-model="notes" aria-label="Catatan transaksi" maxlength="500" rows="2" class="mt-3 w-full rounded-lg border-white/10 bg-white/[0.07] text-xs text-white" placeholder="Catatan transaksi..."></textarea>
<div class="mt-3 grid grid-cols-3 gap-2"><button v-for="method in [{ id:'cash',label:'Tunai'},{id:'qris',label:'QRIS'},{id:'transfer',label:'Transfer'}]" :key="method.id" :aria-pressed="paymentMethod === method.id" class="rounded-lg px-2 py-2 text-xs font-semibold" :class="paymentMethod === method.id ? 'bg-cyan-500 text-slate-950' : 'bg-white/[0.07] text-slate-400'" @click="paymentMethod = method.id">{{ method.label }}</button></div><label class="mt-3 block text-xs text-slate-400">Pembayaran utama<input v-model.number="paidAmount" type="number" min="0" class="mt-1 w-full rounded-lg border-white/10 bg-white/[0.07] text-white"></label><label class="mt-3 flex items-center gap-2 text-xs text-slate-400"><input v-model="split" type="checkbox" class="rounded"> Split payment</label><div v-if="split" class="mt-2 grid grid-cols-2 gap-2"><select v-model="secondMethod" aria-label="Metode pembayaran kedua" class="rounded-lg border-white/10 bg-slate-800 text-xs text-white"><option value="cash" :disabled="paymentMethod === 'cash'">Tunai</option><option value="qris" :disabled="paymentMethod === 'qris'">QRIS</option><option value="transfer" :disabled="paymentMethod === 'transfer'">Transfer</option></select><input v-model.number="secondAmount" aria-label="Nominal pembayaran kedua" type="number" min="0" class="rounded-lg border-white/10 bg-white/[0.07] text-white" placeholder="Nominal kedua"></div><div v-if="change > 0" class="mt-2 flex justify-between text-xs" aria-live="polite"><span class="text-slate-500">Kembalian</span><strong class="text-emerald-400">{{ rupiah(change) }}</strong></div><label class="mt-3 flex items-center gap-2 text-xs text-slate-400"><input v-model="autoPrint" type="checkbox" class="rounded"> Buka struk setelah transaksi</label><button v-if="canCreate" class="mt-4 flex w-full items-center justify-center rounded-xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 disabled:opacity-40" :disabled="!canCheckout" @click="checkout"><span v-if="processing" class="mr-2 size-4 animate-spin rounded-full border-2 border-slate-950/30 border-t-slate-950"></span>{{ processing ? 'Memproses...' : `Bayar ${rupiah(total)}` }}</button></div></aside>
</div></AppLayout></template>
