<script setup lang="ts">
import { computed, reactive } from 'vue';
import { Head, router, usePage } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
const page = usePage<any>(); const mode = computed(() => page.props.mode); const rows = computed(() => page.props.rows ?? []); const ingredients = computed(() => page.props.ingredients ?? []); const outlets = computed(() => page.props.outlets ?? {});
const transfer = reactive({ source: 'transfer', from_outlet_id: '', to_outlet_id: '', note: '', items: [{ ingredient_id: '', quantity: 1 }] });
const opname = reactive({ outlet_id: '', opname_date: new Date().toISOString().slice(0, 10), note: '', items: [{ ingredient_id: '', actual_qty: 0 }] });
const addItem = (items: any[]) => items.push({ ingredient_id: '', quantity: 1, actual_qty: 0 }); const removeItem = (items: any[], index: number) => { if (items.length > 1) items.splice(index, 1); };
function submitTransfer() { router.post('/app/stock-transfers', transfer); } function submitOpname() { router.post('/app/stock-opnames', opname); } function action(id: number, actionName: string) { router.post(`/app/stock-transfers/${id}/${actionName}`); }
</script>
<template><Head :title="mode === 'stock' ? 'Saldo Stok' : mode === 'transfers' ? 'Transfer Stok' : 'Stock Opname'"/><AppLayout><template #title>{{ mode === 'stock' ? 'Saldo Stok' : mode === 'transfers' ? 'Transfer Stok' : 'Stock Opname' }}</template><div class="mx-auto max-w-7xl space-y-6"><div><p class="text-xs font-bold uppercase tracking-[0.22em] text-lime-700">Persediaan</p><h2 class="mt-1 text-2xl font-semibold">{{ mode === 'stock' ? 'Saldo stok outlet' : mode === 'transfers' ? 'Perpindahan stok' : 'Stock opname' }}</h2></div>
<section v-if="mode === 'transfers'" class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="font-semibold">Buat transfer baru</h3><form class="mt-5 space-y-4" @submit.prevent="submitTransfer"><div class="grid gap-4 sm:grid-cols-3"><label class="field">Dari<select v-model="transfer.from_outlet_id"><option value="">Pilih outlet</option><option v-for="(name,id) in outlets" :key="id" :value="id">{{name}}</option></select></label><label class="field">Ke<select v-model="transfer.to_outlet_id"><option value="">Pilih outlet</option><option v-for="(name,id) in outlets" :key="id" :value="id">{{name}}</option></select></label><label class="field">Catatan<input v-model="transfer.note"></label></div><div v-for="(item,index) in transfer.items" :key="index" class="flex gap-2"><select v-model="item.ingredient_id" class="flex-1 rounded-xl border-stone-200"><option value="">Pilih bahan</option><option v-for="ingredient in ingredients" :key="ingredient.id" :value="ingredient.id">{{ingredient.name}} ({{ingredient.unit}})</option></select><input v-model.number="item.quantity" type="number" min="0.001" step="0.001" class="w-32 rounded-xl border-stone-200"><button type="button" class="px-3 text-red-600" @click="removeItem(transfer.items,index)">×</button></div><button type="button" class="text-sm font-semibold text-lime-700" @click="addItem(transfer.items)">+ Tambah bahan</button><button class="block rounded-xl bg-stone-900 px-4 py-3 text-sm font-semibold text-white">Buat transfer</button></form></section>
<section v-if="mode === 'opnames'" class="rounded-3xl border border-stone-200 bg-white p-6 shadow-sm"><h3 class="font-semibold">Buat stock opname</h3><form class="mt-5 space-y-4" @submit.prevent="submitOpname"><div class="grid gap-4 sm:grid-cols-2"><label class="field">Outlet<select v-model="opname.outlet_id"><option value="">Pilih outlet</option><option v-for="(name,id) in outlets" :key="id" :value="id">{{name}}</option></select></label><label class="field">Tanggal<input v-model="opname.opname_date" type="date"></label></div><div v-for="(item,index) in opname.items" :key="index" class="flex gap-2"><select v-model="item.ingredient_id" class="flex-1 rounded-xl border-stone-200"><option value="">Pilih bahan</option><option v-for="ingredient in ingredients" :key="ingredient.id" :value="ingredient.id">{{ingredient.name}} ({{ingredient.unit}})</option></select><input v-model.number="item.actual_qty" type="number" min="0" step="0.001" class="w-32 rounded-xl border-stone-200"><button type="button" class="px-3 text-red-600" @click="removeItem(opname.items,index)">×</button></div><button type="button" class="text-sm font-semibold text-lime-700" @click="addItem(opname.items)">+ Tambah bahan</button><button class="block rounded-xl bg-stone-900 px-4 py-3 text-sm font-semibold text-white">Simpan opname</button></form></section>
<section class="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm"><thead class="border-b bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th class="px-5 py-4">Outlet</th><th class="px-5 py-4">Item</th><th class="px-5 py-4">Status/Qty</th><th class="px-5 py-4">Aksi</th></tr></thead><tbody class="divide-y divide-stone-100"><tr v-for="row in rows" :key="row.id"><td class="px-5 py-4">{{row.outlet?.name ?? row.from_outlet?.name ?? '-'}}</td><td class="px-5 py-4 font-medium">{{row.ingredient?.name ?? row.items?.map((item:any) => `${item.ingredient?.name} x${item.quantity}`).join(', ') ?? `#${row.id}`}}</td><td class="px-5 py-4">{{mode === 'stock' ? row.quantity : row.status}}</td><td class="space-x-2 px-5 py-4"><button v-if="mode === 'transfers' && row.status === 'draft'" class="text-lime-700" @click="action(row.id,'ship')">Kirim</button><button v-if="mode === 'transfers' && ['draft','sent'].includes(row.status)" class="text-emerald-700" @click="action(row.id,'receive')">Terima</button><button v-if="mode === 'transfers' && ['draft','sent'].includes(row.status)" class="text-red-600" @click="action(row.id,'cancel')">Batal</button><button v-if="mode === 'opnames' && row.status === 'draft'" class="text-lime-700" @click="router.post(`/app/stock-opnames/${row.id}/apply`)">Terapkan</button></td></tr><tr v-if="!rows.length"><td colspan="4" class="p-10 text-center text-stone-500">Belum ada data.</td></tr></tbody></table></div></section></div></AppLayout></template>
<style scoped>.field{display:block;color:#57534e;font-size:.8rem}.field input,.field select{display:block;width:100%;margin-top:.35rem;border:1px solid #e7e5e4;border-radius:.8rem;background:#fafaf9;padding:.7rem .8rem;font-size:.875rem;color:#1c1917}</style>
